### PR TITLE
WIP - Switch to Faraday

### PR DESCRIPTION
**Pull request by catlee**

### CODE REVIEW

**Comment by bajajneha27** [comment]
Hi @catlee ,
Thank you for opening this PR. This is going to be a significantly big PR and we'll have to make sure that changes are backward compatible. So before you make further changes, I'd recommend you to keep these two things in mind:
1. The interface doesn't change (currently the interface of `BaseService#client` is being changed. It now returns `FaradayClient` rather than `HTTPClient`), and 
2. No functionality is lost (we'd need to carefully audit all the capabilities of `HTTPClient that are being used and depended on, and make sure they are replicated in the Faraday implementation).

**Comment by catlee** [comment]
> Hi @catlee , Thank you for opening this PR. This is going to be a significantly big PR and we'll have to make sure that changes are backward compatible. So before you make further changes, I'd recommend you to keep these two things in mind:
> 
> 1. The interface shouldn't change. Currently the interface of `BaseService#client` is being changed; It now returns `FaradayClient` rather than `HTTPClient`

This is a pretty significant restriction. Many of the methods in the code pass around a `client` object, which is assumed to be an `HTTPClient` instance. I'm not sure how we can switch to another implementation without changing this contract.

Do you have any suggestions for how to resolve this? I wonder if it's possible to create an adapter for `FaradayClient` that makes it behave like `HTTPClient`...

> 2. No functionality is lost (we'd need to carefully audit all the capabilities of `HTTPClient` that are being used and depended on, and make sure they are replicated in the Faraday implementation). There are a lot of other libraries which are dependent on core library and hence we'll have to be careful.

The test suite seems very comprehensive. Are there areas of particular concern?

**Comment by bajajneha27** [comment]
Hey @catlee 
Sorry it's taking long for us to respond. 
We generally don't allow any breaking change in our libraries; but I get your point. Let me discuss this internally and get back to you. Thank you for your patience!

**Comment by runephilosof-karnovgroup** [comment]
@bajajneha27 Any news?

Since HTTPClient has been unmaintained for a long time, you should also consider whether this is a security issue https://github.com/googleapis/google-api-ruby-client/issues/2348#issuecomment-1099746533
> depending on abandonware that hasn't been touched since 2016 that handles establishing SSL connections is not secure at all

**Comment by hwo411** [comment]
Unfortunately, we had bigger and bigger issues with httpclient, so it'd be great if we can have this ready.

@bajajneha27 are there any updates on this topic? The issue is indeed severe (for us it's like if we touch the code that uses google cloud storage, we then likely need a workaround for a new problem).

**Comment by hwo411** [comment]
Unfortunately, we had bigger and bigger issues with httpclient, so it'd be great if we can have this ready.

@bajajneha27 are there any updates on this topic? The issue is indeed severe (for us it's like if we touch the code that uses google cloud storage, we then likely need a workaround for a new problem).

**Comment by bajajneha27** [comment]
Hi everyone,
Appreciate your patience here. This is rather a big change. Unfortunately, we're not taking any significant feature requests for google-api-ruby-client and hence we won't be able to make this change. We'll circle back if anything pressing comes up.
I'll go ahead and close this PR. Thank you!

**Comment by casperisfine** [comment]
@bajajneha27 I'm not sure if you are aware, but `httpclient` is straight out broken today because it has an old list of CA certificates from 2015 hardcoded in its source: https://github.com/nahi/httpclient/issues/445

I don't understand how this can be considered, "not pressing".

**Comment by casperisfine** [comment]
Now, `httpclient` is broken on Ruby 3.4 because it uses `mutex_m` that has been removed from the stdlib, so the gem would need to update its gemspec.

**Comment by dazuma** [comment]
We'll make sure `mutex_m` is included in the google-apis-core gemspec as needed.

**Comment by mohamedhafez** [comment]
Just registering my disappointment that you guys have open source community members willing to work on a security issue to make a Google product more secure, useable, and future-proof, but are refusing to let them. If breaking changes are an issue, just call it a new major version. A broken 8 year old abandoned SSL implementation is not going to hold forever, and is probably full of security holes as it is since literally nobody has touched that code in coming up on a decade...

**Comment by Firefishy** [comment]
> While we work on moving away from HttpClient, a new [version](https://github.com/googleapis/google-api-ruby-client/releases/tag/google-apis-core%2Fv0.11.2) of gem that patches the client to use systems default root CA path is now released.

Here is the change if anyone is interested: https://github.com/googleapis/google-api-ruby-client/pull/16446

**Comment by wyardley** [comment]
> While we work on moving away from HttpClient, a new [version](https://github.com/googleapis/google-api-ruby-client/releases/tag/google-apis-core%2Fv0.11.2) of gem that patches the client to use systems default root CA path is now released.

Hi @NivedhaSenthil @dazuma - is there any more news on plans for this?

**Pull request closed without merging**
