### PR TITLE
Update OVERVIEW.md

### PR DESCRIPTION
**Pull request by samzhao2008**
There is no `authentication` method for `client`. It should be `authorization`

### CODE REVIEW

**Comment by quartzmo** [comment]
@samzhao2008 This is a generated file. The generator template is located here: https://github.com/googleapis/google-api-ruby-client/blob/main/google-apis-generator/lib/google/apis/generator/templates/overview.md.tmpl

**Comment by samzhao2008** [comment]
@quartzmo so, basically, `overview.md.tmpl` should be corrected?

**Comment by quartzmo** [comment]
@samzhao2008 That is my understanding. Also, be sure to review [CONTRIBUTING.md](.github/CONTRIBUTING.md) regarding the PR process.

**Comment by samzhao2008** [comment]
@quartzmo  Thank you!

**Comment by quartzmo** [comment]
@samzhao2008 Happy to help!

**Pull request closed without merging**
